version: "3.7"

services:
  database:
    image: postgres
    container_name: database-boilerplate-node
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=boilerplate-node
      - POSTGRES_PASSWORD=boilerplate-node
      - POSTGRES_DB=boilerplate-node
    volumes:
      - pgdata:/data/postgres
    networks:
      - boilerplate-node

  server:
    build: .
    container_name: boilerplate-node
    ports:
      - 3333:3333
    depends_on:
      - database
    volumes:
      - .:/usr/app
    networks:
      - boilerplate-node

volumes:
  pgdata:
    driver: local

networks:
  boilerplate-node:
    name: boilerplate-node-network
