version: "3.7"

services:
  server:
    build: .
    container_name: boilerplate-node
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - boilerplate-node

volumes:
  pdgata:
    driver: local

networks:
  boilerplate-node:
    name: boilerplate-node-network